version: "3.9"

services:
  nextjs:
    build: ./ui
    volumes:
      - ./ui:/app
      # - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - nodejs
    environment:
      NODE_ENV: development

  nodejs:
    build: ./api
    volumes:
      - ./api:/app
      # - /app/node_modules
    ports:
      - "8080:8080"
    command: npm run dev
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    # volumes:
    #   - ./data:/data/db
